language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
script: 
  - npm test
after_success:
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/