export const icons = {
    file: 'insert_drive_file',
    word: 'insert_drive_file',
    powerpoint: 'insert_drive_file',
    document: 'insert_drive_file',
    excel: 'insert_drive_file',
    folder: 'folder',
    smartfolder: 'folder_shared',
    image: 'photo',
    rename: 'text_fields',
    copy: 'content_copy',
    move: 'input',
    delete: 'delete',
    clear: 'clear',
    arrowRight: 'keyboard_arrow_right',
    arrowLeft: 'keyboard_arrow_left',
    sharecontent: 'share',
    starcontent: 'star',
    edit: 'mode_edit',
    tick: 'done',
    upload: 'file_upload',
    logout: 'power_settings_new',
    settings: 'settings',
    profile: 'person',
    download: 'file_download',
    share: 'share',
    arrowDropDown: 'arrow_drop_down',
}
