export const resources = {
    EMAIL_IS_NOT_VALID_MESSAGE: 'Please provide a valid e-mail address!',
    PASSWORD_IS_NOT_VALID_MESSAGE: 'Please provide a password!',
    WRONG_USERNAME_OR_PASSWORD: 'Wrong user name or password',
    EMAIL_INPUT_LABEL: 'E-mail',
    PASSWORD_INPUT_LABEL: 'Password',
    EMAIL_INPUT_PLACEHOLDER: 'E-mail',
    PASSWORD_INPUT_PLACEHOLDER: 'Password',
    LOGIN_BUTTON_TEXT: 'Login',
    LOGIN_TAB_TEXT: 'Login',
    REGISTER_TAB_TEXT: 'Register',
    WELCOME_MESSAGE: 'Welcome to the sensenet Document Management System Experiment! We are thrilled to have you here. Please log in, or register!',
    REGISTRATION_BUTTON_TEXT: 'Register',
    EMAIL_INPUT_FORMAT_PLACEHOLDER: 'example@domain.com',
    CONFIRM_PASSWORD_INPUT_LABEL: 'Confirm password',
    PASSWORD_SHOULD_BE_VALID: 'Password needs to contain at least 3 characters!',
    PASSWORDS_SHOULD_MATCH: 'Passwords should match!',
    USER_IS_ALREADY_REGISTERED: 'The email address you have entered is already registered!',
    CAPTCHA_ERROR: 'Please complete the captcha!',
    OPEN_MENU: 'Open menu',
    LOGOUT: 'Logout',
    UPLOAD_BUTTON_TITLE: 'Upload',
    UPLOAD_BUTTON_UPLOAD_FILE_TITLE: 'Upload file',
    UPLOAD_BUTTON_UPLOAD_FOLDER_TITLE: 'Upload folder',
    UPLOAD_BAR_TITLE: 'Uploads',
    UPLOAD_BAR_CLOSE_TITLE: 'Close',
    MYPROFILE: 'My profile',
    SETTINGS: 'Settings',
    ADD_NEW: 'New',
    USER: 'user',
    GROUP: 'group',
    CONTENTTYPE: 'contenttype',
    DOCUMENTS: 'Documents',
    SHARED_WITH_ME: 'Shared with me',
    SAVED_QUERIES: 'Saved queries',
    TRASH: 'Trash',
    USERS: 'Users',
    GROUPS: 'Groups',
    CONTENT_TYPES: 'Content Types',
    CONTENT_TEMPLATES: 'Content Templates',
    CONTENTTEMPLATE: 'Template',
    COMMON: 'Common',
    AD_SYNC: 'AD sync',
    BUILTIN_TYPES: 'Built-in types',
    CUSTOM_TYPES: 'Custom types',
    MY_CUSTOM_TYPES: 'My custom types',
    PREVIEW: 'Preview',
    DELETE: 'Delete',
    ARE_YOU_SURE_YOU_WANT_TO_DELETE: 'Are you sure you want to delete the following(s)?',
    CANCEL: 'Cancel',
    DELETE_PERMANENTLY: 'Delete permanently',
    VERSIONS: 'Versions',
    OK: 'Ok',
    UPLOAD_NEW_VERSION: 'Upload new version',
    VERSIONING_MODE: 'Versioning mode',
    PATH: 'Path',
    VERSIONING: [
        'None',
        'Inherited',
        'Major only',
        'Major and minor',
    ],
    VERSION: 'Version',
    MODIFIED: 'Modified by',
    COMMENT: 'Comment',
    REJECT_REASON: 'Reject reason',
    VERSION_APPROVED: 'Approved',
    VERSION_LOCKED: 'Locked',
    VERSION_DRAFT: 'Draft',
    VERSION_PENDING: 'Pending',
    VERSION_REJECTED: 'Rejected',
}
